[package]
name = "artemis"
edition = "2021"
version = "0.1.0"

[dependencies]
base64 = "0.21.0"
log = "0.4.17"
artemis-core = {path = "../artemis-core"}
clap = {version = "4.2.7", features = ["std", "help", "derive"]}