name: SCC Line Count
on:
  push:
    paths:
      - "**/*.rs"
jobs:
  scc_job:
    runs-on: ubuntu-latest
    name: Count lines of Rust code (includes tests)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the lines of code.
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.2
        with:
          args: ${{ env.workspace }} -i rs --by-file -s complexity
      - name: Echo scc output
        run: echo  "${{ steps.scc.outputs.scc }}"
